language: python
python:
- '3.8'
install:
- pip install -r requirements-travis.txt
- pip install python-social-auth[django]
script:
- python manage.py makemigrations
deploy:
  provider: heroku
  api_key:
    secure: 22b8c023-1071-47a7-9981-4ba11ac27333
  app: scrumptious-quicktutor
  on:
    repo: uva-cs3240-s20/project-101-scrumptious
